---
functional:
  - Пользователь должен иметь возможность выбора языка программирования
  - Пользователю должен быть виден код соперника и результаты запуска тестов в реальном времени
  - У пользователя должна быть возможность общаться в чате с соперноком и зрителями
  - У пользователя должна быть возможность создавать игру самому и ждать случайного соперника
  - У пользователя должна быть возможность отправлять ссылку выбранному сопернику
  - У аользователя должна быть возможность ступать в открытые игры
  - Пользователь должен иметь возможность войти в открытую игру в качестве зрителя
  - У пользователя должна быть возможность следить за открытой игрой без посещения сайта
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность доступа к сайту с помощью выбора языка
  - 
  - 
  - 
  - 
  - 
