---
functional:
  - У пользователя должна быть возможность создавать новую игру с ботом, другом, случайным соперником
  - Пользователь должен иметь возможность выбора языка программирования для сражения
  - Пользователю должен быть виден код соперника и результаты запуска тестов в реальном времени
  - У пользователя должна быть возможность общаться в чате с соперником и зрителями
  - Пользователь должен иметь возможность войти в открытую игру в качестве зрителя
  - У пользователя должна быть возможность следить за открытой игрой без посещения сайта
  - У пользователя должнать быть возможность вступать в открытые игры
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность прочитать задание с помощью выбора языка
  - Пользователь должен иметь возможность вернуться на главную страницу 
  - У пользователя должна быть возможность просматривать рейтинги игроков
  - Пользователю должна быть доступна история пройденных турниров
  - 
  - 
